language: python
python:
 - "3.9"
install:
 - pip install -r requirements.txt
script:
 - python -m unittest tests.test_atom
 - python -m unittest tests.test_molecule
 - python -m unittest tests.test_molecule_parser